const WORDS = [
  { article: "der", noun: "Apfel", english: "apple" },
  { article: "die", noun: "Banane", english: "banana" },
  { article: "das", noun: "Brot", english: "bread" },
  { article: "die", noun: "Butter", english: "butter" },
  { article: "der", noun: "Käse", english: "cheese" },
  { article: "das", noun: "Ei", english: "egg" },
  { article: "das", noun: "Fleisch", english: "meat" },
  { article: "der", noun: "Fisch", english: "fish" },
  { article: "der", noun: "Reis", english: "rice" },
  { article: "die", noun: "Suppe", english: "soup" },

  { article: "der", noun: "Salat", english: "salad" },
  { article: "die", noun: "Kartoffel", english: "potato" },
  { article: "die", noun: "Tomate", english: "tomato" },
  { article: "die", noun: "Zwiebel", english: "onion" },
  { article: "der", noun: "Zucker", english: "sugar" },
  { article: "das", noun: "Salz", english: "salt" },
  { article: "der", noun: "Pfeffer", english: "pepper" },
  { article: "der", noun: "Tee", english: "tea" },
  { article: "der", noun: "Saft", english: "juice" },
  { article: "das", noun: "Bier", english: "beer" },

  { article: "der", noun: "Zug", english: "train" },
  { article: "der", noun: "Bus", english: "bus" },
  { article: "das", noun: "Fahrrad", english: "bicycle" },
  { article: "das", noun: "Flugzeug", english: "airplane" },
  { article: "das", noun: "Schiff", english: "ship" },
  { article: "die", noun: "Straße", english: "street" },
  { article: "der", noun: "Bahnhof", english: "station" },
  { article: "der", noun: "Flughafen", english: "airport" },
  { article: "die", noun: "Stadt", english: "city" },
  { article: "das", noun: "Dorf", english: "village" },

  { article: "die", noun: "Schule", english: "school" },
  { article: "die", noun: "Universität", english: "university" },
  { article: "der", noun: "Lehrer", english: "teacher (m)" },
  { article: "die", noun: "Lehrerin", english: "teacher (f)" },
  { article: "der", noun: "Schüler", english: "pupil (m)" },
  { article: "die", noun: "Schülerin", english: "pupil (f)" },
  { article: "das", noun: "Heft", english: "notebook" },
  { article: "der", noun: "Stift", english: "pen" },
  { article: "der", noun: "Bleistift", english: "pencil" },
  { article: "der", noun: "Radiergummi", english: "eraser" },

  { article: "der", noun: "Computer", english: "computer" },
  { article: "der", noun: "Laptop", english: "laptop" },
  { article: "die", noun: "Maus", english: "mouse" },
  { article: "die", noun: "Tastatur", english: "keyboard" },
  { article: "der", noun: "Bildschirm", english: "screen" },
  { article: "das", noun: "Internet", english: "internet" },
  { article: "die", noun: "E-Mail", english: "email" },
  { article: "das", noun: "Foto", english: "photo" },
  { article: "die", noun: "Musik", english: "music" },
  { article: "der", noun: "Film", english: "film" },

  { article: "das", noun: "Spiel", english: "game" },
  { article: "der", noun: "Ball", english: "ball" },
  { article: "der", noun: "Sport", english: "sport" },
  { article: "das", noun: "Wetter", english: "weather" },
  { article: "die", noun: "Sonne", english: "sun" },
  { article: "der", noun: "Regen", english: "rain" },
  { article: "der", noun: "Schnee", english: "snow" },
  { article: "der", noun: "Wind", english: "wind" },
  { article: "der", noun: "Himmel", english: "sky" },
  { article: "die", noun: "Wolke", english: "cloud" },

  { article: "der", noun: "Morgen", english: "morning" },
  { article: "der", noun: "Abend", english: "evening" },
  { article: "die", noun: "Nacht", english: "night" },
  { article: "der", noun: "Tag", english: "day" },
  { article: "die", noun: "Woche", english: "week" },
  { article: "der", noun: "Monat", english: "month" },
  { article: "das", noun: "Jahr", english: "year" },
  { article: "die", noun: "Uhr", english: "clock/watch" },
  { article: "die", noun: "Minute", english: "minute" },
  { article: "die", noun: "Stunde", english: "hour" },

  { article: "der", noun: "Freund", english: "friend (m)" },
  { article: "die", noun: "Freundin", english: "friend (f)" },
  { article: "die", noun: "Familie", english: "family" },
  { article: "das", noun: "Baby", english: "baby" },
  { article: "der", noun: "Bruder", english: "brother" },
  { article: "die", noun: "Schwester", english: "sister" },
  { article: "der", noun: "Vater", english: "father" },
  { article: "die", noun: "Mutter", english: "mother" },
  { article: "das", noun: "Mädchen", english: "girl" },
  { article: "der", noun: "Junge", english: "boy" },

  { article: "der", noun: "Name", english: "name" },
  { article: "der", noun: "Vorname", english: "first name" },
  { article: "der", noun: "Nachname", english: "last name" },
  { article: "die", noun: "Adresse", english: "address" },
  { article: "die", noun: "Telefonnummer", english: "phone number" },
  { article: "das", noun: "Land", english: "country" },
  { article: "die", noun: "Sprache", english: "language" },
  { article: "das", noun: "Wort", english: "word" },
  { article: "der", noun: "Satz", english: "sentence" },
  { article: "die", noun: "Frage", english: "question" },

  { article: "die", noun: "Antwort", english: "answer" },
  { article: "der", noun: "Fehler", english: "mistake" },
  { article: "die", noun: "Hilfe", english: "help" },
  { article: "die", noun: "Arbeit", english: "work" },
  { article: "der", noun: "Job", english: "job" },
  { article: "das", noun: "Geld", english: "money" },
  { article: "der", noun: "Preis", english: "price" },
  { article: "der", noun: "Markt", english: "market" },
  { article: "das", noun: "Geschäft", english: "shop/business" }

    // ===== ДОДАНІ DER =====
  { article: "der", noun: "Apfel", english: "apple" },
  { article: "der", noun: "Käse", english: "cheese" },
  { article: "der", noun: "Fisch", english: "fish" },
  { article: "der", noun: "Reis", english: "rice" },
  { article: "der", noun: "Salat", english: "salad" },
  { article: "der", noun: "Zucker", english: "sugar" },
  { article: "der", noun: "Pfeffer", english: "pepper" },
  { article: "der", noun: "Tee", english: "tea" },
  { article: "der", noun: "Saft", english: "juice" },
  { article: "der", noun: "Zug", english: "train" },
  { article: "der", noun: "Bus", english: "bus" },
  { article: "der", noun: "Bahnhof", english: "station" },
  { article: "der", noun: "Flughafen", english: "airport" },
  { article: "der", noun: "Lehrer", english: "teacher (m)" },
  { article: "der", noun: "Schüler", english: "pupil (m)" },
  { article: "der", noun: "Stift", english: "pen" },
  { article: "der", noun: "Bleistift", english: "pencil" },
  { article: "der", noun: "Radiergummi", english: "eraser" },
  { article: "der", noun: "Computer", english: "computer" },
  { article: "der", noun: "Laptop", english: "laptop" },
  { article: "der", noun: "Bildschirm", english: "screen" },
  { article: "der", noun: "Film", english: "film" },
  { article: "der", noun: "Ball", english: "ball" },
  { article: "der", noun: "Sport", english: "sport" },
  { article: "der", noun: "Regen", english: "rain" },
  { article: "der", noun: "Schnee", english: "snow" },
  { article: "der", noun: "Wind", english: "wind" },
  { article: "der", noun: "Himmel", english: "sky" },
  { article: "der", noun: "Morgen", english: "morning" },
  { article: "der", noun: "Abend", english: "evening" },
  { article: "der", noun: "Tag", english: "day" },
  { article: "der", noun: "Monat", english: "month" },
  { article: "der", noun: "Freund", english: "friend (m)" },
  { article: "der", noun: "Bruder", english: "brother" },
  { article: "der", noun: "Vater", english: "father" },
  { article: "der", noun: "Junge", english: "boy" },
  { article: "der", noun: "Name", english: "name" },
  { article: "der", noun: "Vorname", english: "first name" },
  { article: "der", noun: "Nachname", english: "last name" },
  { article: "der", noun: "Fehler", english: "mistake" },
  { article: "der", noun: "Job", english: "job" },
  { article: "der", noun: "Preis", english: "price" },
  { article: "der", noun: "Markt", english: "market" },

  // ===== ДОДАНІ DIE =====
  { article: "die", noun: "Banane", english: "banana" },
  { article: "die", noun: "Butter", english: "butter" },
  { article: "die", noun: "Suppe", english: "soup" },
  { article: "die", noun: "Kartoffel", english: "potato" },
  { article: "die", noun: "Tomate", english: "tomato" },
  { article: "die", noun: "Zwiebel", english: "onion" },
  { article: "die", noun: "Straße", english: "street" },
  { article: "die", noun: "Stadt", english: "city" },
  { article: "die", noun: "Schule", english: "school" },
  { article: "die", noun: "Universität", english: "university" },
  { article: "die", noun: "Lehrerin", english: "teacher (f)" },
  { article: "die", noun: "Schülerin", english: "pupil (f)" },
  { article: "die", noun: "Maus", english: "mouse" },
  { article: "die", noun: "Tastatur", english: "keyboard" },
  { article: "die", noun: "Musik", english: "music" },
  { article: "die", noun: "Sonne", english: "sun" },
  { article: "die", noun: "Wolke", english: "cloud" },
  { article: "die", noun: "Nacht", english: "night" },
  { article: "die", noun: "Woche", english: "week" },
  { article: "die", noun: "Uhr", english: "clock/watch" },
  { article: "die", noun: "Minute", english: "minute" },
  { article: "die", noun: "Stunde", english: "hour" },
  { article: "die", noun: "Freundin", english: "friend (f)" },
  { article: "die", noun: "Schwester", english: "sister" },
  { article: "die", noun: "Mutter", english: "mother" },
  { article: "die", noun: "Familie", english: "family" },
  { article: "die", noun: "Adresse", english: "address" },
  { article: "die", noun: "Telefonnummer", english: "phone number" },
  { article: "die", noun: "Sprache", english: "language" },
  { article: "die", noun: "Frage", english: "question" },
  { article: "die", noun: "Antwort", english: "answer" },
  { article: "die", noun: "Hilfe", english: "help" },
  { article: "die", noun: "Arbeit", english: "work" },
  { article: "die", noun: "Familie", english: "family" },

  // ===== ДОДАНІ DAS =====
  { article: "das", noun: "Brot", english: "bread" },
  { article: "das", noun: "Ei", english: "egg" },
  { article: "das", noun: "Fleisch", english: "meat" },
  { article: "das", noun: "Salz", english: "salt" },
  { article: "das", noun: "Fahrrad", english: "bicycle" },
  { article: "das", noun: "Flugzeug", english: "airplane" },
  { article: "das", noun: "Schiff", english: "ship" },
  { article: "das", noun: "Dorf", english: "village" },
  { article: "das", noun: "Heft", english: "notebook" },
  { article: "das", noun: "Internet", english: "internet" },
  { article: "das", noun: "Foto", english: "photo" },
  { article: "das", noun: "Spiel", english: "game" },
  { article: "das", noun: "Wetter", english: "weather" },
  { article: "das", noun: "Jahr", english: "year" },
  { article: "das", noun: "Baby", english: "baby" },
  { article: "das", noun: "Mädchen", english: "girl" },
  { article: "das", noun: "Land", english: "country" },
  { article: "das", noun: "Wort", english: "word" },
  { article: "das", noun: "Geld", english: "money" },
  { article: "das", noun: "Geschäft", english: "shop/business" }


  { article: "die", noun: "Erde", english: "earth/soil" },
  { article: "der", noun: "Mond", english: "moon" },
  { article: "die", noun: "Sonne", english: "sun" },
  { article: "der", noun: "Stern", english: "star" },
  { article: "das", noun: "Universum", english: "universe" },
  { article: "die", noun: "Welt", english: "world" },
  { article: "der", noun: "Kontinent", english: "continent" },
  { article: "das", noun: "Landesinnere", english: "inland" },
  { article: "die", noun: "Küste", english: "coast" },
  { article: "die", noun: "Wüste", english: "desert" },

  { article: "der", noun: "Regenbogen", english: "rainbow" },
  { article: "das", noun: "Gewitter", english: "thunderstorm" },
  { article: "der", noun: "Blitz", english: "lightning" },
  { article: "der", noun: "Donner", english: "thunder" },
  { article: "der", noun: "Nebel", english: "fog" },
  { article: "der", noun: "Frost", english: "frost" },
  { article: "das", noun: "Eis", english: "ice" },
  { article: "die", noun: "Welle", english: "wave" },
  { article: "die", noun: "Flut", english: "flood" },
  { article: "die", noun: "Dürre", english: "drought" },

  { article: "das", noun: "Experiment", english: "experiment" },
  { article: "die", noun: "Wissenschaft", english: "science" },
  { article: "der", noun: "Forscher", english: "researcher (m)" },
  { article: "die", noun: "Forscherin", english: "researcher (f)" },
  { article: "die", noun: "Entdeckung", english: "discovery" },
  { article: "die", noun: "Erfindung", english: "invention" },
  { article: "das", noun: "Labor", english: "laboratory" },
  { article: "die", noun: "Chemie", english: "chemistry" },
  { article: "die", noun: "Physik", english: "physics" },
  { article: "die", noun: "Biologie", english: "biology" },

  { article: "der", noun: "Körper", english: "body" },
  { article: "der", noun: "Geist", english: "mind/spirit" },
  { article: "das", noun: "Blut", english: "blood" },
  { article: "das", noun: "Herz", english: "heart" },
  { article: "die", noun: "Lunge", english: "lung" },
  { article: "der", noun: "Magen", english: "stomach" },
  { article: "die", noun: "Gesundheitspflege", english: "healthcare" },
  { article: "die", noun: "Bewegung", english: "movement" },
  { article: "die", noun: "Ernährung", english: "nutrition" },
  { article: "der", noun: "Schlaf", english: "sleep" },

  { article: "die", noun: "Serie", english: "series" },
  { article: "die", noun: "Sendung", english: "broadcast/show" },
  { article: "der", noun: "Kanal", english: "channel" },
  { article: "die", noun: "Zeitung", english: "newspaper" },
  { article: "die", noun: "Zeitschrift", english: "magazine" },
  { article: "der", noun: "Artikel", english: "article" },
  { article: "die", noun: "Anzeige", english: "advertisement" },
  { article: "die", noun: "Werbung", english: "advertising" },
  { article: "die", noun: "Nachrichtensendung", english: "news program" },
  { article: "der", noun: "Bericht", english: "report" },

  { article: "die", noun: "Kultur", english: "culture" },
  { article: "die", noun: "Tradition", english: "tradition" },
  { article: "der", noun: "Brauch", english: "custom" },
  { article: "das", noun: "Fest", english: "festival/celebration" },
  { article: "die", noun: "Feier", english: "celebration" },
  { article: "die", noun: "Religion", english: "religion" },
  { article: "der", noun: "Glaube", english: "belief/faith" },
  { article: "das", noun: "Gebet", english: "prayer" },
  { article: "die", noun: "Sprache", english: "language" },
  { article: "der", noun: "Dialekt", english: "dialect" },

  { article: "die", noun: "Beziehung", english: "relationship" },
  { article: "die", noun: "Bekanntschaft", english: "acquaintance" },
  { article: "der", noun: "Kollege", english: "colleague" },
  { article: "die", noun: "Nachbarschaft", english: "neighborhood" },
  { article: "die", noun: "Gemeinschaft", english: "community" },
  { article: "die", noun: "Gesellschaft", english: "society" },
  { article: "die", noun: "Bevölkerung", english: "population" },
  { article: "die", noun: "Mehrheit", english: "majority" },
  { article: "die", noun: "Minderheit", english: "minority" },
  { article: "die", noun: "Regierung", english: "government" },

  { article: "das", noun: "System", english: "system" },
  { article: "die", noun: "Politik", english: "politics" },
  { article: "die", noun: "Wahl", english: "election/choice" },
  { article: "die", noun: "Stimme", english: "vote/voice" },
  { article: "das", noun: "Recht", english: "right/law" },
  { article: "die", noun: "Pflicht", english: "duty" },
  { article: "die", noun: "Freiheit", english: "freedom" },
  { article: "die", noun: "Gleichheit", english: "equality" },
  { article: "die", noun: "Meinungsfreiheit", english: "freedom of speech" },
  { article: "die", noun: "Sicherheit", english: "security/safety" }

    { article: "der", noun: "Bleistiftspitzer", english: "pencil sharpener" },
  { article: "das", noun: "Lineal", english: "ruler" },
  { article: "die", noun: "Schere", english: "scissors" },
  { article: "der", noun: "Kleber", english: "glue" },
  { article: "das", noun: "Blatt", english: "sheet/leaf" },
  { article: "das", noun: "Heftchen", english: "booklet" },
  { article: "die", noun: "Tafel", english: "board" },
  { article: "der", noun: "Kurs", english: "course" },
  { article: "die", noun: "Stunde", english: "lesson/hour" },
  { article: "das", noun: "Fach", english: "subject/compartment" },

  { article: "der", noun: "Direktor", english: "director (m)" },
  { article: "die", noun: "Direktorin", english: "director (f)" },
  { article: "der", noun: "Student", english: "student (m)" },
  { article: "die", noun: "Studentin", english: "student (f)" },
  { article: "der", noun: "Professor", english: "professor (m)" },
  { article: "die", noun: "Professorin", english: "professor (f)" },
  { article: "das", noun: "Semester", english: "semester" },
  { article: "die", noun: "Note", english: "grade/mark" },
  { article: "das", noun: "Diplom", english: "diploma" },
  { article: "die", noun: "Ausbildung", english: "education/training" },

  { article: "der", noun: "Bäcker", english: "baker (m)" },
  { article: "die", noun: "Bäckerin", english: "baker (f)" },
  { article: "der", noun: "Fahrer", english: "driver (m)" },
  { article: "die", noun: "Fahrerin", english: "driver (f)" },
  { article: "der", noun: "Verkäufer", english: "seller (m)" },
  { article: "die", noun: "Verkäuferin", english: "seller (f)" },
  { article: "der", noun: "Kellner", english: "waiter" },
  { article: "die", noun: "Kellnerin", english: "waitress" },
  { article: "der", noun: "Mechaniker", english: "mechanic (m)" },
  { article: "die", noun: "Mechanikerin", english: "mechanic (f)" },

  { article: "das", noun: "Werkzeug", english: "tool" },
  { article: "der", noun: "Hammer", english: "hammer" },
  { article: "der", noun: "Nagel", english: "nail" },
  { article: "die", noun: "Schraube", english: "screw" },
  { article: "der", noun: "Schraubenzieher", english: "screwdriver" },
  { article: "die", noun: "Maschine", english: "machine" },
  { article: "die", noun: "Technik", english: "technology" },
  { article: "der", noun: "Motor", english: "engine" },
  { article: "das", noun: "Gerät", english: "device" },
  { article: "der", noun: "Knopf", english: "button" },

  { article: "die", noun: "Lampe", english: "lamp" },
  { article: "die", noun: "Kerze", english: "candle" },
  { article: "das", noun: "Licht", english: "light" },
  { article: "der", noun: "Schatten", english: "shadow" },
  { article: "die", noun: "Dunkelheit", english: "darkness" },
  { article: "die", noun: "Helligkeit", english: "brightness" },
  { article: "die", noun: "Hitze", english: "heat" },
  { article: "die", noun: "Kälte", english: "cold" },
  { article: "die", noun: "Luft", english: "air" },
  { article: "das", noun: "Feuer", english: "fire" },

  { article: "das", noun: "Holz", english: "wood" },
  { article: "der", noun: "Stein", english: "stone" },
  { article: "das", noun: "Metall", english: "metal" },
  { article: "das", noun: "Gold", english: "gold" },
  { article: "das", noun: "Silber", english: "silver" },
  { article: "das", noun: "Glas", english: "glass (material)" },
  { article: "der", noun: "Plastik", english: "plastic" },
  { article: "der", noun: "Stoff", english: "fabric/material" },
  { article: "das", noun: "Leder", english: "leather" },
  { article: "das", noun: "Papierkorb", english: "trash can" },

  { article: "der", noun: "Park", english: "park" },
  { article: "der", noun: "Platz", english: "square/place" },
  { article: "die", noun: "Brücke", english: "bridge" },
  { article: "der", noun: "Turm", english: "tower" },
  { article: "das", noun: "Schloss", english: "castle/lock" },
  { article: "die", noun: "Kirche", english: "church" },
  { article: "die", noun: "Moschee", english: "mosque" },
  { article: "die", noun: "Synagoge", english: "synagogue" },
  { article: "der", noun: "Tempel", english: "temple" },
  { article: "der", noun: "Friedhof", english: "cemetery" },

  { article: "die", noun: "Bank", english: "bench/bank" },
  { article: "die", noun: "Haltestelle", english: "bus stop" },
  { article: "die", noun: "Ampel", english: "traffic light" },
  { article: "der", noun: "Verkehr", english: "traffic" },
  { article: "das", noun: "Autohaus", english: "car dealer" },
  { article: "die", noun: "Werkstatt", english: "workshop/garage" },
  { article: "die", noun: "Tankstelle", english: "gas station" },
  { article: "der", noun: "Fahrplan", english: "timetable" },
  { article: "die", noun: "Verspätung", english: "delay" },
  { article: "die", noun: "Fahrt", english: "journey/ride" },

  { article: "das", noun: "Glück", english: "luck" },
  { article: "das", noun: "Pech", english: "bad luck" },
  { article: "der", noun: "Erfolg", english: "success" },
  { article: "der", noun: "Misserfolg", english: "failure" },
  { article: "die", noun: "Hoffnung", english: "hope" },
  { article: "die", noun: "Geduld", english: "patience" },
  { article: "der", noun: "Stress", english: "stress" },
  { article: "die", noun: "Ruhe", english: "calm/quiet" },
  { article: "der", noun: "Lärm", english: "noise" },
  { article: "das", noun: "Chaos", english: "chaos" },

  { article: "die", noun: "Ordnung", english: "order/tidiness" },
  { article: "der", noun: "Planer", english: "planner" },
  { article: "der", noun: "Kalender", english: "calendar" },
  { article: "die", noun: "App", english: "app" },
  { article: "das", noun: "Programm", english: "program" },
  { article: "die", noun: "Webseite", english: "website" },
  { article: "das", noun: "Passwort", english: "password" },
  { article: "der", noun: "Benutzer", english: "user (m)" },
  { article: "die", noun: "Benutzerin", english: "user (f)" },
  { article: "der", noun: "Fehlercode", english: "error code" }

];








