const WORDS = [
  { article: "der", noun: "Apfel", english: "apple" },
  { article: "die", noun: "Banane", english: "banana" },
  { article: "das", noun: "Brot", english: "bread" },
  { article: "die", noun: "Butter", english: "butter" },
  { article: "der", noun: "Käse", english: "cheese" },
  { article: "das", noun: "Ei", english: "egg" },
  { article: "das", noun: "Fleisch", english: "meat" },
  { article: "der", noun: "Fisch", english: "fish" },
  { article: "der", noun: "Reis", english: "rice" },
  { article: "die", noun: "Suppe", english: "soup" },

  { article: "der", noun: "Salat", english: "salad" },
  { article: "die", noun: "Kartoffel", english: "potato" },
  { article: "die", noun: "Tomate", english: "tomato" },
  { article: "die", noun: "Zwiebel", english: "onion" },
  { article: "der", noun: "Zucker", english: "sugar" },
  { article: "das", noun: "Salz", english: "salt" },
  { article: "der", noun: "Pfeffer", english: "pepper" },
  { article: "der", noun: "Tee", english: "tea" },
  { article: "der", noun: "Saft", english: "juice" },
  { article: "das", noun: "Bier", english: "beer" },

  { article: "der", noun: "Zug", english: "train" },
  { article: "der", noun: "Bus", english: "bus" },
  { article: "das", noun: "Fahrrad", english: "bicycle" },
  { article: "das", noun: "Flugzeug", english: "airplane" },
  { article: "das", noun: "Schiff", english: "ship" },
  { article: "die", noun: "Straße", english: "street" },
  { article: "der", noun: "Bahnhof", english: "station" },
  { article: "der", noun: "Flughafen", english: "airport" },
  { article: "die", noun: "Stadt", english: "city" },
  { article: "das", noun: "Dorf", english: "village" },

  { article: "die", noun: "Schule", english: "school" },
  { article: "die", noun: "Universität", english: "university" },
  { article: "der", noun: "Lehrer", english: "teacher (m)" },
  { article: "die", noun: "Lehrerin", english: "teacher (f)" },
  { article: "der", noun: "Schüler", english: "pupil (m)" },
  { article: "die", noun: "Schülerin", english: "pupil (f)" },
  { article: "das", noun: "Heft", english: "notebook" },
  { article: "der", noun: "Stift", english: "pen" },
  { article: "der", noun: "Bleistift", english: "pencil" },
  { article: "der", noun: "Radiergummi", english: "eraser" },

  { article: "der", noun: "Computer", english: "computer" },
  { article: "der", noun: "Laptop", english: "laptop" },
  { article: "die", noun: "Maus", english: "mouse" },
  { article: "die", noun: "Tastatur", english: "keyboard" },
  { article: "der", noun: "Bildschirm", english: "screen" },
  { article: "das", noun: "Internet", english: "internet" },
  { article: "die", noun: "E-Mail", english: "email" },
  { article: "das", noun: "Foto", english: "photo" },
  { article: "die", noun: "Musik", english: "music" },
  { article: "der", noun: "Film", english: "film" },

  { article: "das", noun: "Spiel", english: "game" },
  { article: "der", noun: "Ball", english: "ball" },
  { article: "der", noun: "Sport", english: "sport" },
  { article: "das", noun: "Wetter", english: "weather" },
  { article: "die", noun: "Sonne", english: "sun" },
  { article: "der", noun: "Regen", english: "rain" },
  { article: "der", noun: "Schnee", english: "snow" },
  { article: "der", noun: "Wind", english: "wind" },
  { article: "der", noun: "Himmel", english: "sky" },
  { article: "die", noun: "Wolke", english: "cloud" },

  { article: "der", noun: "Morgen", english: "morning" },
  { article: "der", noun: "Abend", english: "evening" },
  { article: "die", noun: "Nacht", english: "night" },
  { article: "der", noun: "Tag", english: "day" },
  { article: "die", noun: "Woche", english: "week" },
  { article: "der", noun: "Monat", english: "month" },
  { article: "das", noun: "Jahr", english: "year" },
  { article: "die", noun: "Uhr", english: "clock/watch" },
  { article: "die", noun: "Minute", english: "minute" },
  { article: "die", noun: "Stunde", english: "hour" },

  { article: "der", noun: "Freund", english: "friend (m)" },
  { article: "die", noun: "Freundin", english: "friend (f)" },
  { article: "die", noun: "Familie", english: "family" },
  { article: "das", noun: "Baby", english: "baby" },
  { article: "der", noun: "Bruder", english: "brother" },
  { article: "die", noun: "Schwester", english: "sister" },
  { article: "der", noun: "Vater", english: "father" },
  { article: "die", noun: "Mutter", english: "mother" },
  { article: "das", noun: "Mädchen", english: "girl" },
  { article: "der", noun: "Junge", english: "boy" },

  { article: "der", noun: "Name", english: "name" },
  { article: "der", noun: "Vorname", english: "first name" },
  { article: "der", noun: "Nachname", english: "last name" },
  { article: "die", noun: "Adresse", english: "address" },
  { article: "die", noun: "Telefonnummer", english: "phone number" },
  { article: "das", noun: "Land", english: "country" },
  { article: "die", noun: "Sprache", english: "language" },
  { article: "das", noun: "Wort", english: "word" },
  { article: "der", noun: "Satz", english: "sentence" },
  { article: "die", noun: "Frage", english: "question" },

  { article: "die", noun: "Antwort", english: "answer" },
  { article: "der", noun: "Fehler", english: "mistake" },
  { article: "die", noun: "Hilfe", english: "help" },
  { article: "die", noun: "Arbeit", english: "work" },
  { article: "der", noun: "Job", english: "job" },
  { article: "das", noun: "Geld", english: "money" },
  { article: "der", noun: "Preis", english: "price" },
  { article: "der", noun: "Markt", english: "market" },
  { article: "das", noun: "Geschäft", english: "shop/business" }
];
